databases:
  # A free PostgreSQL Database for our application
  - name: database
    plan: free

services:
  # A free Redis instance for the chat's channel layer
  - type: redis
    name: redis
    plan: free
    ipAllowList: [] # Allows connections only from other services in your Render account

  # The main Django Web Service, now running ONLY daphne
  - type: web
    name: echo-chamber-web
    runtime: python
    plan: free
    buildCommand: "chmod +x ./build.sh && ./build.sh"
    # Daphne will now handle both HTTP and WebSocket traffic
    startCommand: "daphne -b 0.0.0.0 -p $PORT blog_project.asgi:application"
    disks:
      - name: media-storage
        mountPath: /app/media
        sizeGB: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will create a secure secret key for you
      - key: PYTHON_VERSION
        value: 3.10.0
