services:
  # A free PostgreSQL Database for our application
  - type: pserv
    name: database
    plan: free
    # (Render will automatically use the latest stable version)

  # A free Redis instance for the chat's channel layer
  - type: redis
    name: redis
    plan: free

  # The main Django Web Service (runs gunicorn)
  - type: web
    name: echo-chamber-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will create a secure secret key for you
      - key: PYTHON_VERSION
        value: 3.10.0

  # The Worker for our Live Chat (runs daphne)
  - type: worker
    name: echo-chamber-chat
    env: python
    plan: free
    startCommand: "daphne -b 0.0.0.0 -p 10000 blog_project.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        # This syncs the secret key from the web service we defined above
        fromService:
          type: web
          name: echo-chamber-web
          envVarKey: SECRET_KEY
